### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/wm#1]
- [ ] actions
    - [ ] center
    - [ ] fullscreen
    - [ ] kill
    - [ ] desktop focus
    - [ ] desktop send
    - [ ] focus next
- [ ] events
- [ ] misc
    - [ ] clean up extern/static/whatever.
    - [ ] sort out desktop global.
    - [ ] create client type if needed (just using window ids now).

**Comment by pfr-dev** [comment]
This is looking cool mate, excited to see it when it's done. You really are an sh wizard!

**Comment by dylanaraps** [comment]
Thanks I'm not really working on this anymore though. :)
